
function Verb(infinitive, simple, participle, meaning)
{
	this.infinitive = infinitive;
	this.simple = simple;
	this.participle = participle;
	this.meaning = meaning;
}

function Round(min, max)
{
	this.roundVector = new Array();

	//max+1 because slice doesn't get the last index
	this.roundVector = verbBucket.slice(min, max+1);
}

verbBucket = new Array();

verbBucket.push(new Verb("ask","asked","asked","Say something in order to obtain an answer or some information/ Say to (someone) that one wants them to do or give something"));
verbBucket.push(new Verb("awake","awoke","awoken","Stop sleeping"));
verbBucket.push(new Verb("be","was/were","been","Exist/ Occur; take place"));
verbBucket.push(new Verb("bear","bore","born","Carry/ Support/ Endure/ Carry the weight of"));
verbBucket.push(new Verb("beat","beat","beaten","Strike (a person or an animal) repeatedly and violently so as to hurt or injure them, typically with an implement such as a club or whip/ Defeat (someone) in a game or other competitive situation"));
verbBucket.push(new Verb("become","became","become","Begin to be/ (of clothing) Look good on or suit (someone)"));
verbBucket.push(new Verb("begin","began","begun","Perform or undergo the first part of (an action or activity)"));
verbBucket.push(new Verb("believe","believed","believed","Accept that (something) is true, especially without proof/ Feel sure of the truth of/ Hold (something) as an opinion; think"));
verbBucket.push(new Verb("bend","bent","bent","Shape or force (something straight) into a curve or angle/(of a person) Incline the body downward from the vertical"));
verbBucket.push(new Verb("bet","bet","bet","Risk something, usually a sum of money, against someone else's on the basis of the outcome of a future event, such as the result of a race or game/ Feel sure"));
verbBucket.push(new Verb("bid","bid","bid","Offer (a certain price) for something, especially at an auction/ Make an effort or attempt to achieve"));
verbBucket.push(new Verb("bind","bound","bound","Tie or fasten (something) tightly/ Stick together or cause to stick together in a single mass"));
verbBucket.push(new Verb("bite","bit","bitten","Use the teeth to cut into something in order to eat it/ (of a tool, tire, boot, etc.) Grip or take hold on a surface"));
verbBucket.push(new Verb("bleed","bled","bled","Lose blood from the body as a result of injury or illness/ Draw blood from (someone), especially as a former method of treatment in medicine"));
verbBucket.push(new Verb("blow","blew","blown","(of wind) Move creating an air current/ (of a person) Expel air through pursed lips"));
verbBucket.push(new Verb("break","broke","broken","Separate or cause to separate into pieces as a result of a blow, shock, or strain/ Interrupt (a continuity, sequence, or course)"));
verbBucket.push(new Verb("breed","bred","bred","(of animals) Mate and then produce offspring"));
verbBucket.push(new Verb("bring","brought","brought","Take or go with (someone or something) to a place/ Cause (someone or something) to be in a particular state or condition"));
verbBucket.push(new Verb("broadcast","broadcast","broadcast","Transmit (a program or some information) by radio or television/ Scatter (seeds) by hand or machine rather than placing in drills or rows"));
verbBucket.push(new Verb("build","built","built","Construct (something) by putting parts or material together"));
verbBucket.push(new Verb("burn","burnt","burnt","(of a fire) Flame or glow while consuming a material such as coal or wood/ Be or cause to be destroyed by fire/ (of a person, the skin, or a part of the body) Become red and painful through exposure to the sun"));
verbBucket.push(new Verb("burst","burst","burst","(of a container) break suddenly and violently apart, spilling the contents, typically as a result of an impact or internal pressure"));
verbBucket.push(new Verb("bust","bust","bust","To go bankrupt/to collapse from the strain of making a supreme effort"));
verbBucket.push(new Verb("buy","bought","bought","Obtain in exchange for payment"));
verbBucket.push(new Verb("call","called","called","Cry out to (someone) in order to summon them or attract their attention/Give (an infant or animal) a specified name"));
verbBucket.push(new Verb("cast","cast","cast","Throw (something) forcefully in a specified direction/Cause (light or shadow) to appear on a surface"));
verbBucket.push(new Verb("catch","caught","caught","Intercept and hold (something that has been thrown, propelled, or dropped)/Capture (a person or animal that tries or would try to escape)"));
verbBucket.push(new Verb("choose","chose","chosen","Pick out or select (someone or something) as being the best or most appropriate of two or more alternatives"));
verbBucket.push(new Verb("clap","clapped","clapped","Strike the palms of (one's hands) together repeatedly, typically in order to applaud"));
verbBucket.push(new Verb("cling","clung","clung","(of a person or animal) hold on tightly to"));
verbBucket.push(new Verb("come","came","come","Move or travel toward or into a place thought of as near or familiar to the speaker/Occur; happen; take place"));
verbBucket.push(new Verb("cost","cost","cost","(of an object or an action) require the payment of (a specified sum of money) before it can be acquired or done/Estimate the price of"));
verbBucket.push(new Verb("creep","crept","crept","Move slowly and carefully, especially in order to avoid being heard or noticed/(of an unwanted and negative characteristic or fact) occur or develop gradually and almost imperceptibly"));
verbBucket.push(new Verb("cut","cut","cut","Make an opening, incision, or wound in (something) with a sharp-edged tool or object/Remove (something) from something larger by using a sharp implement"));
verbBucket.push(new Verb("dare","dared","dared","Have the courage to do something/ Defy or challenge (someone) to do something"));
verbBucket.push(new Verb("deal","dealt","dealt","Distribute (cards) in an orderly rotation to the players for a game or round/ Take part in commercial trading of a particular commodity"));
verbBucket.push(new Verb("dig","dug","dug","Break up and move earth with a tool or machine, or with hands, paws, snout, etc/ Like, appreciate, or understand"));
verbBucket.push(new Verb("dive","dived","dived","Plunge head first into water/ (of an aircraft or bird) Plunge steeply downward through the air"));
verbBucket.push(new Verb("do","did","done","Perform (an action, the precise nature of which is often unspecified)/ Achieve or complete, in particular/ Used before a verb (except be, can, may, ought, shall, will ) in questions and negative statements/ Used to refer to a verb already mentioned"));
verbBucket.push(new Verb("draw","drew","drawn","Produce (a picture or diagram) by making lines and marks, especially with a pen or pencil, on paper/ Pull or drag (something such as a vehicle) so as to make it follow behind"));
verbBucket.push(new Verb("dream","dreamt","dreamt","Experience dreams during sleep/ Contemplate the possibility of doing something or that something might be the case"));
verbBucket.push(new Verb("drink","drank","drunk","Take (a liquid) into the mouth and swallow/ Watch or listen to something with eager pleasure or interest"));
verbBucket.push(new Verb("drive","drove","driven","Operate and control the direction and speed of a motor vehicle/ Propel or carry along by force in a specified direction"));
verbBucket.push(new Verb("eat","ate","eaten","Put (food) into the mouth and chew and swallow it"));
verbBucket.push(new Verb("fall","fell","fallen","Move downward, typically rapidly and freely without control, from a higher to a lower level/ (of a person) Lose one's balance and collapse"));
verbBucket.push(new Verb("feed","fed","fed","Give food to/ Supply (a machine) with material, power, or other things necessary for its operation"));
verbBucket.push(new Verb("feel","felt","felt","Be aware of (a person or object) through touching or being touched/ Experience (an emotion or sensation)"));
verbBucket.push(new Verb("fight","fought","fought","Take part in a violent struggle involving the exchange of physical blows or the use of weapons/ "));
verbBucket.push(new Verb("find","found","found","discover or perceive by chance or unexpectedly/ identify (something) as being present "));
verbBucket.push(new Verb("fit","fit","fit","be of the right shape and size for/ install or fix (something) into place"));
verbBucket.push(new Verb("flee","fled","fled","run away from a place or situation of danger/ run away from (someone or something)"));
verbBucket.push(new Verb("fling","flung","flung","throw or hurl forcefully"));
verbBucket.push(new Verb("fly","flew","flown","(of a bird, bat, or insect) move through the air using wings/ move or be hurled quickly through the air"));
verbBucket.push(new Verb("forbid","forbade","forbidden","refuse to allow (something)/ order (someone) not to do something/ refuse entry to a place or area"));
verbBucket.push(new Verb("forecast","forecast","forecast","predict or estimate (a future event or trend)"));
verbBucket.push(new Verb("foresee","foresaw","foreseen","be aware of beforehand; predict"));
verbBucket.push(new Verb("forget","forgot","forgotten","fail to remember/ inadvertently neglect to do or mention something/ deliberately cease to think of"));
verbBucket.push(new Verb("forgive","forgave","forgiven","stop feeling angry or resentful towards (someone) for an offence, flaw, or mistake/ no longer feel angry about or wish to punish (an offence, flaw, or mistake)/ cancel (a debt)"));
verbBucket.push(new Verb("forsake","forsook","forsaken","abandon or leave/ renounce or give up (something valued or pleasant)"));
verbBucket.push(new Verb("freeze","froze","frozen","(with reference to a liquid) turn or be turned into ice or another solid as a result of extreme cold/ store (something) at a very low temperature in order to preserve it"));
verbBucket.push(new Verb("get","got","got","come to have (something); receive/ succeed in attaining, achieving, or experiencing; obtain"));
verbBucket.push(new Verb("give","gave","given","freely transfer the possession of (something) to (someone)/ cause or allow (someone or something) to have or experience (something); provide with"));
verbBucket.push(new Verb("go","went","gone/been","move from one place to another; travel/ leave; depart"));
verbBucket.push(new Verb("grind","ground","ground","reduce (something) to small particles or powder by crushing it/ rub or cause to rub together gratingly"));
verbBucket.push(new Verb("grow","grew","grown","(of a living thing) undergo natural development by increasing in size and changing physically/ come into existence and develop"));
verbBucket.push(new Verb("handwrite","handwrote","handwritten","write by hand"));
verbBucket.push(new Verb("hang","hung","hung","suspend or be suspended from above with the lower part dangling free/ kill (someone) by tying a rope attached from above around their neck and removing the support from beneath them (often used as a form of capital punishment)"));
verbBucket.push(new Verb("have","had","had","possess, own, or hold/ experience; undergo/ used with a past participle to form the perfect, pluperfect, and future perfect tenses, and the conditional mood"));
verbBucket.push(new Verb("hear","heard","heard","perceive with the ear the sound made by (someone or something)/ be told or informed of"));
verbBucket.push(new Verb("help","helped","helped","make it easier or possible for (someone) to do something by offering them one's services or resources/ serve someone with (food or drink)"));
verbBucket.push(new Verb("hide","hid","hidden","put or keep out of sight"));
verbBucket.push(new Verb("hit","hit","hit","bring one's hand or a tool or weapon into contact with (someone or something) quickly and forcefully/ cause harm or distress to"));
verbBucket.push(new Verb("hold","held","held","grasp, carry, or support with one's arms or hands/ keep or detain (someone)"));
verbBucket.push(new Verb("hurt","hurt","hurt","cause pain or injury to/ be detrimental to"));
verbBucket.push(new Verb("inlay","inlaid","inlaid","ornament (an object) by embedding pieces of a different material in it, flush with its surface"));
verbBucket.push(new Verb("input","input","input","put (data) into a computer"));
verbBucket.push(new Verb("keep","kept","kept","have or retain possession of/ continue or cause to continue in a specified condition, position, course, etc"));
verbBucket.push(new Verb("kneel","knelt","knelt","be in or assume a position in which the body is supported by a knee or the knees, as when praying or showing submission"));
verbBucket.push(new Verb("knit","knit","knit","make (a garment or other item) by interlocking loops of wool or other yarn with knitting needles or on a machine/ unite or cause to unite"));
verbBucket.push(new Verb("know","knew","known","be aware of through observation, inquiry, or information/ have developed a relationship with (someone) through meeting and spending time with them; be familiar or friendly with."));
verbBucket.push(new Verb("lay","laid","laid","put (something) down gently or carefully/ put down and set in position for use"));
verbBucket.push(new Verb("lead","led","led","cause (a person or animal) to go with one by holding them by the hand, a halter, a rope, etc. while moving forward/ be a route or means of access to a particular place or in a particular direction"));
verbBucket.push(new Verb("lean","leant","leant","be in or move into a sloping position"));
verbBucket.push(new Verb("leap","leapt","leapt","jump or spring a long way, to a great height, or with great force/ select"));
verbBucket.push(new Verb("learn","learnt","learnt","select/ move quickly and suddenly"));
verbBucket.push(new Verb("leave","left","left","go away from/ allow or cause to remain"));
verbBucket.push(new Verb("lend","lent","lent","grant to (someone) the use of (something) on the understanding that it will be returned/ contribute or add (a quality) to"));
verbBucket.push(new Verb("let","let","let","not prevent or forbid; allow/ used in the imperative to formulate various expressions"));
verbBucket.push(new Verb("lie","lay","lain","(of a person or animal) be in or assume a horizontal or resting position on a supporting surface/ be, remain, or be kept in a specified state"));
verbBucket.push(new Verb("light","lit","lit","provide with light or lighting; illuminate/ make (something) start burning; ignite"));
verbBucket.push(new Verb("like","liked","liked","find agreeable, enjoyable, or satisfactory/ wish for; want"));
verbBucket.push(new Verb("live","lived","lived","remain alive/ make one's home in a particular place or with a particular person"));
verbBucket.push(new Verb("look","looked","looked","direct one's gaze in a specified direction/ regard in a specified way"));
verbBucket.push(new Verb("lose","lost","lost","be deprived of or cease to have or retain (something)/ become unable to find (something or someone)"));
verbBucket.push(new Verb("make","made","made","To cause to exist or happen; bring about; create/ To bring into existence by shaping, modifying, or putting together material; construct"));
verbBucket.push(new Verb("mean","meant","meant","intend to convey or refer to (a particular thing); signify/ intend (something) to occur or be the case"));
verbBucket.push(new Verb("meet","met","met","arrange or happen to come into the presence or company of (someone)/ touch; join"));
verbBucket.push(new Verb("melt","melted","molten","make or become liquefied by heating/ make or become more tender or loving"));
verbBucket.push(new Verb("mislead","misled","misled","cause (someone) to have a wrong idea or impression"));
verbBucket.push(new Verb("mistake","mistook","mistaken","be wrong about"));
verbBucket.push(new Verb("misunderstand","misunderstood","misunderstood","fail to interpret or understand (something) correctly/ fail to interpret or understand the words or actions of (someone) correctly"));
verbBucket.push(new Verb("move","moved","moved","go in a specified direction or manner; change position/ make progress; develop in a particular manner or direction"));
verbBucket.push(new Verb("mow","mowed","mown","cut down (grass) with a machine/ cut down (grass or a cereal crop) with a scythe"));
verbBucket.push(new Verb("need","needed","needed","require (something) because it is essential or very important rather than just desirable/ expressing necessity or obligation"));
verbBucket.push(new Verb("overdraw","overdrew","overdrawn","draw money from (one's bank account) in excess of what the account holds/ exaggerate in describing or depicting (someone or something)"));
verbBucket.push(new Verb("overhear","overheard","overheard","hear (someone or something) without meaning to or without the knowledge of the speaker"));
verbBucket.push(new Verb("overtake","overtook","overtaken","catch up with and pass while travelling in the same direction/ (especially of misfortune) come suddenly or unexpectedly upon"));
verbBucket.push(new Verb("pay","paid","paid","give (someone) money that is due for work done, goods received, or a debt incurred/ suffer a misfortune as a consequence of an action"));
verbBucket.push(new Verb("play","played","played","engage in activity for enjoyment and recreation rather than a serious or practical purpose/ take part in (a sport)"));
verbBucket.push(new Verb("preset","preset","preset","set or adjust (a value that controls the operation of a device) in advance of its use"));
verbBucket.push(new Verb("prove","proved","proven","demonstrate the truth or existence of (something) by evidence or argument/ demonstrate to be the specified thing by evidence or argument"));
verbBucket.push(new Verb("put","put","put","move to or place in a particular position/ bring into a particular state or condition"));
verbBucket.push(new Verb("quit","quit","quit","leave (a place), usually permanently"));
verbBucket.push(new Verb("read","read","read","look at and comprehend the meaning of (written or printed matter) by interpreting the characters or symbols of which it is composed/ discover (information) by reading it in a written or printed source"));
verbBucket.push(new Verb("rid","rid","rid","make someone or something free of (an unwanted person or thing)/ be freed or relieved of"));
verbBucket.push(new Verb("ride","rode","ridden","sit on and control the movement of (an animal, typically a horse)/ be carried or supported by (something moving with great momentum)"));
verbBucket.push(new Verb("ring","rang","rung","surround (someone or something), especially for protection or containment/ put an aluminium strip around the leg of (a bird) for subsequent identification"));
verbBucket.push(new Verb("rise","rose","risen","move from a lower position to a higher one; come or go up/ get up from lying, sitting, or kneeling"));
verbBucket.push(new Verb("run","ran","run","move at a speed faster than a walk, never having both or all the feet on the ground at the same time/ pass or cause to pass quickly in a particular direction"));
verbBucket.push(new Verb("saw","sawed","sawn","cut (something) using a saw"));
verbBucket.push(new Verb("say","said","said","utter words so as to convey information, an opinion, a feeling or intention, or an instruction/ assume something in order to work out what its consequences would be; make a hypothesis"));
verbBucket.push(new Verb("see","saw","seen","perceive with the eyes; discern visually/ discern or deduce after reflection or from information; understand"));
verbBucket.push(new Verb("seem","seemed","seemed","give the impression of being something or having a particular quality/ be unable to do something, despite having tried"));
verbBucket.push(new Verb("seek","sought","sought","attempt to find (something)/ attempt or desire to obtain or achieve (something)	/ ask for (something) from someone"));
verbBucket.push(new Verb("sell","sold","sold","give or hand over (something) in exchange for money/ persuade someone of the merits of"));
verbBucket.push(new Verb("send","sent","sent","cause to go or be taken to a particular destination; arrange for the delivery of, especially by post/ cause to be in a specified state"));
verbBucket.push(new Verb("set","set","set","put, lay, or stand (something) in a specified place or position/ put or bring into a specified state"));
verbBucket.push(new Verb("sew","sewed","sewn","Join, fasten, or repair (something) by making stitches with a needle and thread"));
verbBucket.push(new Verb("shake","shook","shaken","(of a structure or area of land) tremble or vibrate/ move (an object) up and down or from side to side with rapid, forceful, jerky movements"));
verbBucket.push(new Verb("shave","shaved","shaven","(of a man) cut the hair off the face with a razor/ cut (a thin slice or slices) from the surface of something"));
verbBucket.push(new Verb("shine","shone","shone","(of the sun or another source of light) give out a bright light/ be very talented or perform very well"));
verbBucket.push(new Verb("shoot","shot","shot","kill or wound (a person or animal) with a bullet or arrow/ move or cause to move suddenly and rapidly in a particular direction"));
verbBucket.push(new Verb("show","showed","shown","be, allow, or cause to be visible/ allow (a quality or emotion) to be perceived; display"));
verbBucket.push(new Verb("shrink","shrank","shrunk","become or make smaller in size or amount/ move back or away, especially because of fear or disgust"));
verbBucket.push(new Verb("shut","shut","shut","move (something) into position so as to block an opening; close/ old or bring together the sides of (something) so as to close it"));
verbBucket.push(new Verb("sing","sang","sung","make musical sounds with the voice, especially words with a set tune/ make a high-pitched whistling or buzzing sound"));
verbBucket.push(new Verb("sink","sank","sunk","go down below the surface of something, especially of a liquid; become submerged/ descend from a higher to a lower position; drop downwards"));
verbBucket.push(new Verb("sit","sat","sat","adopt or be in a position in which one's weight is supported by one's buttocks rather than one's feet and one's back is upright/ be or remain in a particular position or state"));
verbBucket.push(new Verb("slay","slew","slain","kill (a person or animal) in a violent way"));
verbBucket.push(new Verb("sleep","slept","slept","A natural periodic state of rest for the mind and body, in which the eyes usually close and consciousness is completely or partially lost, so that there is a decrease in bodily movement and responsiveness to external stimuli"));
verbBucket.push(new Verb("slide","slid","slid","move smoothly along a surface while maintaining continuous contact with it"));
verbBucket.push(new Verb("sling","slung","slung","suspend or arrange (something), especially with a strap or straps, so that it hangs loosely in a particular position/ casually throw or fling"));
verbBucket.push(new Verb("slit","slit","slit","make a long, narrow cut in/ squint"));
verbBucket.push(new Verb("smell","smelt","smelt","perceive or detect the odour or scent of (something)/ emit an odour or scent of a specified kind"));
verbBucket.push(new Verb("sneak","sneaked","sneaked","move or go in a furtive or stealthy way/ (especially in children's use) inform an adult or person in authority of a companion's misdeeds; tell tales"));
verbBucket.push(new Verb("sow","sowed","sown","Plant (seed) by scattering it on or in the earth/ disseminate or introduce (something undesirable)"));
verbBucket.push(new Verb("speak","spoke","spoken","say something in order to convey information or to express a feeling/ talk to in order to reprove or advise"));
verbBucket.push(new Verb("speed","sped","sped","move quickly"));
verbBucket.push(new Verb("spell","spelt","spelt","Write or name the letters that form (a word) in correct sequence"));
verbBucket.push(new Verb("spend","spent","spent","give (money) to pay for goods, services, or so as to benefit someone or something/ pass (time) in a specified way or in a particular place"));
verbBucket.push(new Verb("spill","spilt","spilt","cause or allow (liquid) to flow over the edge of its container, especially unintentionally/ reveal (confidential information) to someone"));
verbBucket.push(new Verb("spin","span","spun","turn or whirl round quickly/ draw out and twist (the fibres of wool, cotton, or other material) to convert them into yarn, either by hand or with machinery"));
verbBucket.push(new Verb("spit","spat","spat","eject saliva forcibly from one's mouth, sometimes as a gesture of contempt or anger/ light rain falls"));
verbBucket.push(new Verb("split","split","split","break or cause to break forcibly into parts, especially into halves or along the grain/ (with reference to a group of people) divide into two or more groups"));
verbBucket.push(new Verb("spoil","spoilt","spoilt","diminish or destroy the value or quality of/ harm the character of (a child) by being too lenient or indulgent"));
verbBucket.push(new Verb("spread","spread","spread","open out (something) so as to extend its surface area, width, or length/ extend over a large or increasing area"));
verbBucket.push(new Verb("spring","sprang","sprung","ove or jump suddenly or rapidly upwards or forwards/ originate or arise from"));
verbBucket.push(new Verb("stand","stood","stood","have or maintain an upright position, supported by one's feet/ (of an object, building, or settlement) be situated in a particular place or position"));
verbBucket.push(new Verb("start","started","started","begin or be reckoned from a particular point in time or space; come into being/ cause to happen or begin"));
verbBucket.push(new Verb("steal","stole","stolen","take (another person's property) without permission or legal right and without intending to return it/ move somewhere quietly or surreptitiously"));
verbBucket.push(new Verb("stick","stuck","stuck","push a sharp or pointed object into or through (something)/ insert, thrust, or push/ be fixed in a particular position or unable to move or be moved"));
verbBucket.push(new Verb("sting","stung","stung","To pierce or wound painfully with or as if with a sharp-pointed structure or organ, as that of certain insects/ swindle or exorbitantly overcharge (someone)"));
verbBucket.push(new Verb("stink","stank","stunk","have a strong unpleasant smell/ be very unpleasant, contemptible, or scandalous"));
verbBucket.push(new Verb("strike","struck","struck","hit forcibly and deliberately with one's hand or a weapon or other implement/ (of a disaster, disease, or other unwelcome phenomenon) occur suddenly and have harmful or damaging effects on"));
verbBucket.push(new Verb("string","strung","strung","hang (something) so that it stretches in a long line"));
verbBucket.push(new Verb("strip","stript","stript","remove all coverings from/ leave bare of accessories or fittings"));
verbBucket.push(new Verb("strive","strove","striven","make great efforts to achieve or obtain something/ struggle or fight vigorously"));
verbBucket.push(new Verb("swear","swore","sworn","make a solemn statement or promise undertaking to do something or affirming that something is the case/ use offensive language, especially as an expression of anger"));
verbBucket.push(new Verb("sweat","sweat","sweat","To excrete perspiration through the pores in the skin; perspire"));
verbBucket.push(new Verb("sweep","swept","swept","clean (an area) by brushing away dirt or litter/ move swiftly and smoothly"));
verbBucket.push(new Verb("swell","swelled","swollen","(especially of a part of the body) become larger or rounder in size, typically as a result of an accumulation of fluid/ become or make greater in intensity, number, amount, or volume"));
verbBucket.push(new Verb("swim","swam","swum","propel the body through water by using the limbs, or (in the case of a fish or other aquatic animal) by using fins, tail, or other bodily movement/ be immersed in or covered with liquid"));
verbBucket.push(new Verb("swing","swung","swung","move or cause to move back and forth or from side to side while suspended or on an axis/ move by grasping a support from below and leaping"));
verbBucket.push(new Verb("take","took","taken","lay hold of (something) with one's hands; reach for and hold/ Remove (someone or something) from a particular place"));
verbBucket.push(new Verb("talk","talked","talked","speak in order to give information or express ideas or feelings; converse or communicate by spoken words/ have formal dealings or discussions; negotiate"));
verbBucket.push(new Verb("teach","taught","taught","impart knowledge to or instruct (someone) as to how to do something/ cause (someone) to learn or understand something by example or experience"));
verbBucket.push(new Verb("tear","tore","torn","pull (something) apart or to pieces with force/ move very quickly in a reckless or excited manner"));
verbBucket.push(new Verb("tell","told","told","communicate information to someone in spoken or written words/ decide or determine correctly or with certainty"));
verbBucket.push(new Verb("think","thought","thought","have a particular belief or idea/ direct one's mind towards someone or something; use one's mind actively to form connected ideas"));
verbBucket.push(new Verb("throw","threw","thrown","propel (something) with force through the air by a movement of the arm and hand/ send suddenly into a particular state or condition"));
verbBucket.push(new Verb("thrust","thrust","thrust","push suddenly or violently in a specified direction"));
verbBucket.push(new Verb("tread","trod","trodden","walk in a specified way"));
verbBucket.push(new Verb("try","tried","tried","make an attempt or effort to do something/ subject (someone) to trial"));
verbBucket.push(new Verb("turn","turned","turned","move or cause to move in a circular direction wholly or partly around an axis or point/ move (something) so that it is in a different position in relation to its surroundings or its previous position"));
verbBucket.push(new Verb("understand","understood","understood","perceive the intended meaning of (words, a language, or a speaker)/ interpret or view (something) in a particular way"));
verbBucket.push(new Verb("upset","upset","upset","make (someone) unhappy, disappointed, or worried/ knock (something) ove"));
verbBucket.push(new Verb("use","used","used","take, hold, or deploy (something) as a means of accomplishing or achieving something; employ/ take or consume (an amount) from a limited supply"));
verbBucket.push(new Verb("wake","woke","woken","emerge or cause to emerge from sleep; stop sleeping"));
verbBucket.push(new Verb("want","wanted","wanted","have a desire to possess or do (something); wish for"));
verbBucket.push(new Verb("wear","wore","worn","have (something) on one's body as clothing, decoration, or protection/ damage, erode, or destroy by friction or use"));
verbBucket.push(new Verb("weep","wept","wept","shed tears/ used in names of tree and shrub varieties with drooping branches, e.g. weeping cherry"));
verbBucket.push(new Verb("wet","wet","wet","cover or touch with liquid; moisten"));
verbBucket.push(new Verb("win","won","won","be successful or victorious in (a contest or conflict)/ acquire or secure as a result of a contest, conflict, bet, or other endeavour"));
verbBucket.push(new Verb("wind","wound","wound","cause (someone) to have difficulty breathing because of exertion or a blow to the stomach"));
verbBucket.push(new Verb("withdraw","withdrew","withdrawn","remove or take away (something) from a particular place or position/ leave or cause to leave a place or situation"));
verbBucket.push(new Verb("withhold","withheld","withheld","refuse to give (something that is due to or is desired by another)/ suppress or hold back (an emotion or reaction)"));
verbBucket.push(new Verb("withstand","withstood","withstood","remain undamaged or unaffected by; resist/ offer strong resistance or opposition to"));
verbBucket.push(new Verb("work","worked","worked","be engaged in physical or mental activity in order to achieve a result/ (of a machine or system) function, especially properly or effectively"));
verbBucket.push(new Verb("wring","wrung","wrung","squeeze and twist (something) to force liquid from it/ break (an animal's neck) by twisting it forcibly"));
verbBucket.push(new Verb("write","wrote","written","mark (letters, words, or other symbols) on a surface, typically paper, with a pen, pencil, or similar implement/ compose, write, and send (a letter) to someone"));